name: MLOps Pipeline

on:
  push:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Train model
        run: python src/train.py

      - name: Run Tests
        run: pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # ✅ match earlier job for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training & quantization
        run: |
          python src/train.py
          python src/quantize.py

  build-and-test-container:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mlops-linear .

      - name: Run Docker container
        run: docker run --rm mlops-linear
